---
apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: stock           # Name of the Kubernetes resource
spec:
  replicas: 1                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: stock        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: stock 
    spec:                        # Spec for the container which will run in the Pod
      containers:
      - name: stock
        image: mannanmcc/stock:1.0.1
        imagePullPolicy: IfNotPresent
        ports:
          - name: stock
            containerPort: 50051
        resources:
          limits:
            cpu: 50m
            memory: 124Mi
          requests:
            cpu: 50m
            memory: 124Mi