---
apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: order           # Name of the Kubernetes resource
spec:
  replicas: 1                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: order        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: order
    spec:                        # Spec for the container which will run in the Pod
      containers:
      - name: order
        image: mannanmcc/order:1.0.2
        imagePullPolicy: IfNotPresent
        ports:
          - name: order
            containerPort: 50051  # Should match the port number that the Go application listens on
        #Set the spec.containers.envFrom.configMapRef field to pull a ConfigMap’s data into a pod’s containers as environment variables:
        envFrom:
          - configMapRef:
              name: order
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 64Mi

---
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: order-service   # Name of the resource
spec:
  type: LoadBalancer
  ports:                         # Take incoming HTTP requests on port 5052 and forward them to the targetPort of 50051
    - name: grpc
      port: 50052 # port which this loadbalancer is listen to
      targetPort: 50051 #port which application listen to
  selector:
    app: order         # Map any pod with label `app=go-hello-world` to this service